/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/5.1/userguide/multi_project_builds.html
 */

rootProject.name = "scalatron"

include("BotWar")
include("Scalatron")
include("ScalatronCLI")
include("ScalatronCore")
include("ScalaMarkdown")

/*
File("Bots").listFiles { file -> file.isDirectory }.forEach { dir ->
 include(dir.name)
 project(":${dir.name}").projectDir = dir
}
*/

include("BreadcrumbBot")
project(":BreadcrumbBot").projectDir = File("Bots/BreadcrumbBot")

include("DeepThought")
project(":DeepThought").projectDir = File("Bots/DeepThought")

include("KewlBot")
project(":KewlBot").projectDir = File("Bots/KewlBot")

include("Overmind")
project(":Overmind").projectDir = File("Bots/Overmind")

include("ScourgeOfScala")
project(":ScourgeOfScala").projectDir = File("Bots/ScourgeOfScala")

include("ReferenceBot")
project(":ReferenceBot").projectDir = File("Bots/ReferenceBot")

include("aibot")
project(":aibot").projectDir = File("Bots/aibot")